server:
      port: 8081
      context-path: /user

spring:
    datasource:
             url: jdbc:h2:mem:mydb
             driverClassName: org.h2.Driver
             username: sa
             password: password
    h2:
      console:
             enabled: true
             path: /h2

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        properties:
              hibernate:
                      format_sql: true
                      dialect: org.hibernate.dialect.H2Dialect
                      ddl-auto: update
              validator:
                    apply_to_ddl: false










